[package]
name = "rpv-selfsigned"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["cdylib", "rlib"]

[dependencies]
rustls-platform-verifier = "0.2.0"
rustls = "0.22.2"

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.19"
